### ISSUE TITLE
LICENSE copyright 

### ISSUE THREAD

**Issue by Bpazy** [bingoohuang/westcache#1]
https://github.com/bingoohuang/westcache/blob/09842bf0b9299abe75551c4b51d326fcc96da42d/LICENSE#L189
这个是不是需要修改下

**Comment by bingoohuang** [comment]
哈哈，都从来没看过里面内容。你要用westcache?

**Comment by Bpazy** [comment]
是因为看到了j2cache这个缓存框架内置了一点防击穿的功能，就想到了缓存框架有没有必要内置这种功能，所以过来看看westcache的代码:flushed:
